inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

# local repo-specific modifications

AllCops:
  TargetRubyVersion: 2.4

# This one breaks plenty of RSpec idioms.
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

# Defining a constant or class inside RSpec.describe block
# sometimes makes sense.
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"

# This requirement is silly to me.
Style/AccessModifierDeclarations:
  Enabled: false

# Makes little sense for Glossarist models, as these attr_accessors should all
# be documented eventually.
Style/AccessorGrouping:
  Enabled: false

# This requirement is silly to me.
Style/ClassCheck:
  Enabled: false

# This requirement is silly to me.
Style/SingleArgumentDig:
  Enabled: false
